# Generated by Django 5.1 on 2024-09-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20240923_1542'),
    ]

    operations = [
    ]
