# Generated by Django 5.1 on 2024-09-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_manufactured_at_and_more'),
    ]

    operations = [
    ]
