# Generated by Django 5.1 on 2024-10-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20240923_1902'),
    ]

    operations = [
    ]
