# Generated by Django 4.2.2 on 2024-11-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_author_product_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='token',
        ),
    ]
